repo:
  - ./*
test:
  - testsuite/**/*
microsoft:
  - "**/mssqlserver-*/**/*"
  - "**/microsoft/**/*"
oracle:
  - "**/oracle/**/*"
  - "**/oracle-*/**/*"
postgresql:
  - "**/postgresql/**/*" 
  - "**/postgresql-*/**/*"
documentation:
  - doc/**/*
 
